[build]
builder = "nixpacks"

[build.nixpacksOptions]
cmds = ["npm install", "npm run build"]

[deploy]
startCommand = "npx serve -s dist -l tcp://0.0.0.0:$PORT"

[[deploy.environmentVariables]]
name = "NODE_ENV"
value = "production"
