[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[deploy.environmentVariables]]
name = "PYTHONPATH"
value = "/app"

[[deploy.environmentVariables]]  
name = "PORT"
value = "8000"
